# Generated by Django 4.2.11 on 2024-05-08 16:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipoUsuario', models.CharField(default='USUARIO', max_length=20)),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)])),
                ('apellidoMaterno', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)])),
                ('apellidoPaterno', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)])),
                ('edad', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('ubicacion', models.CharField(choices=[('AGUASCALIENTES', 'Aguascalientes'), ('BAJA_CALIFORNIA', 'Baja California'), ('BAJA_CALIFORNIA_SUR', 'Baja California Sur'), ('CAMPECHE', 'Campeche'), ('CHIAPAS', 'Chiapas'), ('CHIHUAHUA', 'Chihuahua'), ('CIUDAD_DE_MEXICO', 'Ciudad de México'), ('COAHUILA', 'Coahuila'), ('COLIMA', 'Colima'), ('DURANGO', 'Durango'), ('ESTADO_DE_MEXICO', 'Estado de México'), ('GUANAJUATO', 'Guanajuato'), ('GUERRERO', 'Guerrero'), ('HIDALGO', 'Hidalgo'), ('JALISCO', 'Jalisco'), ('MICHOACAN', 'Michoacán'), ('MORELOS', 'Morelos'), ('NAYARIT', 'Nayarit'), ('NUEVO_LEON', 'Nuevo León'), ('OAXACA', 'Oaxaca'), ('PUEBLA', 'Puebla'), ('QUERETARO', 'Querétaro'), ('QUINTANA_ROO', 'Quintana Roo'), ('SAN_LUIS_POTOSI', 'San Luis Potosí'), ('SINALOA', 'Sinaloa'), ('SONORA', 'Sonora'), ('TABASCO', 'Tabasco'), ('TAMAULIPAS', 'Tamaulipas'), ('TLAXCALA', 'Tlaxcala'), ('VERACRUZ', 'Veracruz'), ('YUCATAN', 'Yucatán'), ('ZACATECAS', 'Zacatecas')], default='Ciudad de México', max_length=50)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO'), ('NO_ESPECIFICADO', 'NO ESPECIFICADO')], default='FEMENINO', max_length=20)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(15)])),
                ('usuario', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)])),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('correo', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()])),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fotos', models.ImageField(blank=True, upload_to='fotos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('ACOSO', 'Acoso'), ('SPAM', 'Spam'), ('CONTENIDO_INAPROPIADO', 'Contenido inapropiado'), ('FRAUDE', 'Fraude')], default='', max_length=21)),
                ('comentario', models.TextField(max_length=500, null=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reportado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match1', to=settings.AUTH_USER_MODEL)),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario1', 'usuario2')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('envia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='like_envia', to=settings.AUTH_USER_MODEL)),
                ('recibe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='like_recibe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('envia', 'recibe')},
            },
        ),
    ]
