# Generated by Django 4.2.11 on 2024-05-28 03:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipoUsuario', models.CharField(choices=[('ADMIN', 'ADMIN'), ('USUARIO', 'USUARIO')], default='USUARIO', max_length=20)),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)])),
                ('apellidoMaterno', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)])),
                ('apellidoPaterno', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)])),
                ('edad', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)])),
                ('ubicacion', models.CharField(choices=[('AGUASCALIENTES', 'Aguascalientes'), ('BAJA_CALIFORNIA', 'Baja California'), ('BAJA_CALIFORNIA_SUR', 'Baja California Sur'), ('CAMPECHE', 'Campeche'), ('CHIAPAS', 'Chiapas'), ('CHIHUAHUA', 'Chihuahua'), ('CIUDAD_DE_MEXICO', 'Ciudad de México'), ('COAHUILA', 'Coahuila'), ('COLIMA', 'Colima'), ('DURANGO', 'Durango'), ('ESTADO_DE_MEXICO', 'Estado de México'), ('GUANAJUATO', 'Guanajuato'), ('GUERRERO', 'Guerrero'), ('HIDALGO', 'Hidalgo'), ('JALISCO', 'Jalisco'), ('MICHOACAN', 'Michoacán'), ('MORELOS', 'Morelos'), ('NAYARIT', 'Nayarit'), ('NUEVO_LEON', 'Nuevo León'), ('OAXACA', 'Oaxaca'), ('PUEBLA', 'Puebla'), ('QUERETARO', 'Querétaro'), ('QUINTANA_ROO', 'Quintana Roo'), ('SAN_LUIS_POTOSI', 'San Luis Potosí'), ('SINALOA', 'Sinaloa'), ('SONORA', 'Sonora'), ('TABASCO', 'Tabasco'), ('TAMAULIPAS', 'Tamaulipas'), ('TLAXCALA', 'Tlaxcala'), ('VERACRUZ', 'Veracruz'), ('YUCATAN', 'Yucatán'), ('ZACATECAS', 'Zacatecas')], default='Ciudad de México', max_length=50)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO'), ('NO_ESPECIFICADO', 'NO ESPECIFICADO')], default='FEMENINO', max_length=20)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(15)])),
                ('usuario', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)])),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('BLOQUEADO', 'BLOQUEADO'), ('ELIMINADO', 'ELIMINADO')], default='ACTIVO', max_length=20)),
                ('correo', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=255)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('orientacionSexual', models.CharField(choices=[('HETEROSEXUAL', 'HETEROSEXUAL'), ('HOMOSEXUAL', 'HOMOSEXUAL'), ('BISEXUAL', 'BISEXUAL'), ('OTRO', 'OTRO')], default='HETEROSEXUAL', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('ACOSO', 'Acoso'), ('SPAM', 'Spam'), ('CONTENIDO_INAPROPIADO', 'Contenido inapropiado'), ('FRAUDE', 'Fraude')], default='', max_length=100)),
                ('comentario', models.TextField(max_length=500, null=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conLentes', models.BooleanField(default=False)),
                ('conCaraOvalada', models.BooleanField(default=False)),
                ('conPielBlanca', models.BooleanField(default=False)),
                ('colorCabello', models.CharField(choices=[('BLACK_HAIR', 'Black_Hair'), ('BLOND_HAIR', 'Blond_Hair'), ('BROWN_HAIR', 'Brown_Hair'), ('GRAY_HAIR', 'Gray_Hair')], default='Black_Hair', max_length=50)),
                ('tipoCabello', models.CharField(choices=[('STRAIGHT_HAIR', 'Straight_Hair'), ('WAVY_HAIR', 'Wavy_Hair')], default='Straight_Hair', max_length=50)),
                ('sexoPreferido', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO'), ('AMBOS', 'AMBOS')], default='AMBOS', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.MaxValueValidator(3)])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AtributosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caraOvalada', models.BooleanField(default=False)),
                ('lentes', models.BooleanField(default=False)),
                ('pielBlanca', models.BooleanField(default=False)),
                ('colorCabello', models.CharField(default='', max_length=50)),
                ('tipoCabello', models.CharField(default='', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match1', to=settings.AUTH_USER_MODEL)),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario1', 'usuario2')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('envia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_envia', to=settings.AUTH_USER_MODEL)),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_recibe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('envia', 'recibe')},
            },
        ),
    ]
