# Generated by Django 4.2.11 on 2024-04-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='USUARIO', max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('correo', models.EmailField(max_length=50)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdministrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='ADMIN', max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('correo', models.EmailField(max_length=50)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
