# Generated by Django 4.2.11 on 2024-05-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotos',
            field=models.TextField(blank=True, default=''),
        ),
    ]
