# Generated by Django 4.2.11 on 2024-05-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
