# Generated by Django 4.2.11 on 2024-05-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
