# Generated by Django 4.2.11 on 2024-05-02 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('NO_ESPECIFICADO', 'No especificado')], default='Femenino', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
