# Generated by Django 4.2.11 on 2024-05-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_latitud_usuario_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='longitud',
        ),
    ]
