# Generated by Django 4.2.11 on 2024-05-20 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_like_envia_alter_like_recibe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caraOvalada', models.BooleanField(default=False)),
                ('lentes', models.BooleanField(default=False)),
                ('pielBlanca', models.BooleanField(default=False)),
                ('colorCabello', models.CharField(default='', max_length=50)),
                ('tipoCabello', models.CharField(default='', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
