# Generated by Django 4.2.11 on 2024-05-20 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_atributosusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conLentes', models.BooleanField(default=False)),
                ('conCaraOvalada', models.BooleanField(default=False)),
                ('conPielBlanca', models.BooleanField(default=False)),
                ('colorCabello', models.CharField(choices=[('BLACK_HAIR', 'Black_Hair'), ('BLOND_HAIR', 'Blond_Hair'), ('BROWN_HAIR', 'Brown_Hair'), ('GRAY_HAIR', 'Gray_Hair')], default='Black_Hair', max_length=50)),
                ('tipoCabello', models.CharField(choices=[('STRAIGHT_HAIR', 'Straight_Hair'), ('WAVY_HAIR', 'Wavy_Hair')], default='Straight_Hair', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
