# Generated by Django 4.2.11 on 2024-06-05 21:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_preferenciasusuario_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciasusuario',
            name='etiquetas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, choices=[('AMOR', 'Amor'), ('VIDEOJUEGOS', 'Videojuegos'), ('DEPORTES', 'Deportes'), ('MUSICA', 'Musica'), ('PELICULAS', 'Películas'), ('SERIES', 'Series'), ('ANIME', 'Anime'), ('VIAJAR', 'Viajar'), ('GYM', 'Gym'), ('LECTURA', 'Lectura'), ('COCINAR', 'Cocinar'), ('FOTOGRAFIA', 'Fotografia'), ('SENDERISMO', 'Senderismo'), ('NATURALEZA', 'Naturaleza'), ('MODA', 'Moda'), ('BAILAR', 'Bailar')], default=list, null=True, size=None),
        ),
    ]
