# Generated by Django 4.2.11 on 2024-05-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_match_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioAdministrador',
        ),
    ]
