# Generated by Django 4.2.11 on 2024-05-05 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_usuarioadministrador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='accepted',
            new_name='aceptado',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_at',
            new_name='fechaRegistro',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='created_at',
            new_name='fechaRegistro',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='like',
            name='envia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='like_envia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='recibe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='like_recibe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='usuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('envia', 'recibe')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='like',
            name='sender',
        ),
    ]
