# Generated by Django 4.2.11 on 2024-05-06 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_usuario_correo_alter_usuario_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('ACOSO', 'Acoso'), ('SPAM', 'Spam'), ('CONTENIDO_INAPROPIADO', 'Contenido inapropiado'), ('FRAUDE', 'Fraude')], default='', max_length=21)),
                ('comentario', models.TextField(max_length=500, null=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reportado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
