# Generated by Django 4.2.11 on 2024-05-13 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mensajechatpersonal',
            name='chat_personal',
        ),
        migrations.RemoveField(
            model_name='mensajechatpersonal',
            name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='mensajechatpersonal',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='mensajegrupal',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='mensajegrupal',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='chatpersonal',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ChatGrupal',
        ),
        migrations.DeleteModel(
            name='MensajeChatPersonal',
        ),
        migrations.DeleteModel(
            name='MensajeGrupal',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatApp.chatpersonal'),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
