# Generated by Django 4.2.11 on 2024-05-13 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatApp', '0002_chat_mensajechat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatpersonal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer_usuario_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatpersonal',
            name='usuario_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_usuario_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajechat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to='chatApp.chatpersonal'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_envia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_recibe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
