# Generated by Django 4.2.11 on 2024-05-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_alter_chatpersonal_usuario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatPersonalManager',
        ),
    ]
