# Generated by Django 4.2.11 on 2024-05-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0004_rename_chat_chatpersonalmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatPersonalManager',
        ),
    ]
