# Generated by Django 4.2.11 on 2024-05-05 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatApp', '0004_chatgrupal_chatperonal_mensaje_mensajegrupal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatPeronal',
            new_name='ChatPersonal',
        ),
    ]
