# Generated by Django 4.2.11 on 2024-05-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0006_mensajechatpersonal_delete_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajechatpersonal',
            old_name='receptor',
            new_name='recipient_id',
        ),
        migrations.RenameField(
            model_name='mensajechatpersonal',
            old_name='emisor',
            new_name='sender_id',
        ),
    ]
